In [113]:
import numpy as np
import numpy.linalg as la

# Uncomment for decimals
np.set_printoptions(formatter={})

In [114]:
# Matrix definieren
A = np.array([
    [3, 2, 2],
    [3, 3, 2],
    [3, 3, 2]
])

In [115]:
# Charakteristisches Polynom
p = np.poly(A)
print('Charakteristisches Polynom:')
print(f'{p[0]}*lambda^2 + {p[1]}*lambda + {round(p[2], 4)}')
print(f'p: {p[1]}, q: {round(p[2], 4)}\n')

# Eigenwerte
eigen = la.eig(A)
eigenwerte = eigen[0]
for i, eig in enumerate(eigenwerte):
    print(f'Lambda {i+1}: {eig}, Gerundet: {np.round(eig, 4)}')

# Eigenvektoren
print(f'')
eigenvektoren = eigen[1]
for i, eig in enumerate(eigenvektoren):
    print(f'Vektor {i+1}:')
    for v in eig:
        print(f'{v}, Gerundet: {round(v, 4)}')

Charakteristisches Polynom:
1.0*lambda^2 + -8.0*lambda + 3.0
p: -8.0, q: 3.0

Lambda 1: 0.3944487245360113, Gerundet: 0.3944
Lambda 2: 7.60555127546399, Gerundet: 7.6056
Lambda 3: 0.0, Gerundet: 0.0

Vektor 1:
-0.7354905461905702, Gerundet: -0.7355
0.523324441698562, Gerundet: 0.5233
-0.5547001962252287, Gerundet: -0.5547
Vektor 2:
0.4790895826796367, Gerundet: 0.4791
0.6025493874865728, Gerundet: 0.6025
-5.225583569541859e-16, Gerundet: -0.0
Vektor 3:
0.4790895826796367, Gerundet: 0.4791
0.6025493874865728, Gerundet: 0.6025
0.8320502943378438, Gerundet: 0.8321


In [116]:
print('Matrix mit Eigenvektoren V:')
print(np.around(eigenvektoren, 4))
print('\nMatrix mit Eigenwerten Lambda:')
print(np.diag(eigenwerte))
print('\nMatrix mit Eigenvektoren V.T:')
print(np.around(eigenvektoren, 4).T)
print('\nV*Lambda*V')

Matrix mit Eigenvektoren V:
[[-0.7355  0.5233 -0.5547]
 [ 0.4791  0.6025 -0.    ]
 [ 0.4791  0.6025  0.8321]]

Matrix mit Eigenwerten Lambda:
[[0.39444872 0.         0.        ]
 [0.         7.60555128 0.        ]
 [0.         0.         0.        ]]

Matrix mit Eigenvektoren V.T:
[[-0.7355  0.4791  0.4791]
 [ 0.5233  0.6025  0.6025]
 [-0.5547 -0.      0.8321]]
