In [4]:
import numpy as np
import numpy.linalg as la

In [5]:
# Definition von X tilde
X_tilde = np.array([
    [1, 1],
    [3, 2],
    [4, 4],
    [6, 7]
])

### Hauptkomponentenzerlegung

In [6]:
m = X_tilde.shape[0]
M = np.eye(m) - np.ones(m)/m
print(f'Zentrierende Matrix M =\n{M}')

X = M@X_tilde
print(f'\nZentrierte Datenmatrix X =\n {X}')

C = X.T@X/(m-1)
print(f'\nKovarianzmatrix C =\n {C}')

HA = la.eig(C)[1]
print('\nHauptachsen:')
print(f'v1:{HA.T[0]}, Gerundet: {np.around(HA.T[0], 4)}')
print(f'v2:{HA.T[1]}, Gerundet: {np.around(HA.T[1], 4)}')

Zentrierende Matrix M =
[[ 0.75 -0.25 -0.25 -0.25]
 [-0.25  0.75 -0.25 -0.25]
 [-0.25 -0.25  0.75 -0.25]
 [-0.25 -0.25 -0.25  0.75]]

Zentrierte Datenmatrix X =
 [[-2.5 -2.5]
 [-0.5 -1.5]
 [ 0.5  0.5]
 [ 2.5  3.5]]

Kovarianzmatrix C =
 [[4.33333333 5.33333333]
 [5.33333333 7.        ]]

Hauptachsen:
v1:[-0.78820544  0.61541221], Gerundet: [-0.7882  0.6154]
v2:[-0.61541221 -0.78820544], Gerundet: [-0.6154 -0.7882]
