In [30]:
import numpy as np
import numpy.linalg as la

In [31]:
# Definition von X tilde
X_tilde = np.array([
    [1, 2],
    [3, -1],
    [5, -2],
    [8, -3],
    [9, -5]
])

### Hauptkomponentenzerlegung

In [35]:
m = X_tilde.shape[0]
M = np.eye(m) - np.ones(m)/m
print(f'M =\n{M}')

X = M@X_tilde
print(f'\nZentrierte Datenmatrix X =\n {X}')

C = X.T@X/(m-1)
print(f'\nKovarianzmatrix C =\n {C}')

HA = la.eig(C)[1]
print('\nHauptachsen:')
print(f'v1:{HA.T[0]}, Gerundet: {np.around(HA.T[0], 4)}')
print(f'v2:{HA.T[1]}, Gerundet: {np.around(HA.T[1], 4)}')

M =
[[ 0.8 -0.2 -0.2 -0.2 -0.2]
 [-0.2  0.8 -0.2 -0.2 -0.2]
 [-0.2 -0.2  0.8 -0.2 -0.2]
 [-0.2 -0.2 -0.2  0.8 -0.2]
 [-0.2 -0.2 -0.2 -0.2  0.8]]

Zentrierte Datenmatrix X =
 [[-4.2  3.8]
 [-2.2  0.8]
 [-0.2 -0.2]
 [ 2.8 -1.2]
 [ 3.8 -3.2]]

Kovarianzmatrix C =
 [[11.2 -8.3]
 [-8.3  6.7]]
Hauptachsen:
v1:[ 0.79424215 -0.60760136], Gerundet: [ 0.7942 -0.6076]
v2:[0.60760136 0.79424215], Gerundet: [0.6076 0.7942]
