In [10]:
import numpy as np
import numpy.linalg as la
from scipy.linalg import lu

In [11]:
# Matrizen definieren, Inverse, Eigenwerte usw. wird nur von Matrix A berechnet
A = np.array([
    [5, 3, 5],
    [5, 2, 9],
    [2, 3, 4]
])
B = np.array([
    [1, 3, 5],
    [5, 2, 9],
    [2, 3, 4]
])

print(f'A = \n {A}')
print(f'B = \n {B}')

A = 
 [[5 3 5]
 [5 2 9]
 [2 3 4]]
B = 
 [[1 3 5]
 [5 2 9]
 [2 3 4]]


### Determinante

In [12]:
det = la.det(A)
print(f'{det}, Gerundet: {round(det, 2)}')

-45.999999999999986, Gerundet: -46.0


### Inverse

In [13]:
inv = la.inv(A)
print(f'Inverse:\n{inv}')
print(f'Gerundet:\n{np.around(inv, 2)}')

Inverse:
[[ 0.41304348 -0.06521739 -0.36956522]
 [ 0.04347826 -0.2173913   0.43478261]
 [-0.23913043  0.19565217  0.10869565]]
Gerundet:
[[ 0.41 -0.07 -0.37]
 [ 0.04 -0.22  0.43]
 [-0.24  0.2   0.11]]


### Transformation

In [14]:
A.T

array([[5, 5, 2],
       [3, 2, 3],
       [5, 9, 4]])

### Matrixmultiplikation

In [15]:
np.matmul(A, B)

array([[30, 36, 72],
       [33, 46, 79],
       [25, 24, 53]])

### Eigenwerte

In [16]:
eigenwerte = la.eigvals(A)
for i, eig in enumerate(eigenwerte):
    print(f'Lambda {i+1}: {eig}, Gerundet: {round(eig, 2)}')

Lambda 1: 11.853688000659918, Gerundet: 11.85
Lambda 2: 1.588805917410658, Gerundet: 1.59
Lambda 3: -2.4424939180705834, Gerundet: -2.44


### Eigenvektoren

In [17]:
eigenvektoren = la.eig(A)[1]
for i, eig in enumerate(eigenvektoren):
    print(f'Vektor {i+1}:')
    for v in eig:
        print(f'{v}, Gerundet: {round(v, 2)}')

Vektor 1:
-0.6012535141979378, Gerundet: -0.6
-0.8608605423319998, Gerundet: -0.86
0.104182002897443, Gerundet: 0.1
Vektor 2:
-0.6833570191446267, Gerundet: -0.68
0.19674238743227285, Gerundet: 0.2
-0.9135848464127081, Gerundet: -0.91
Vektor 3:
-0.4141465876358279, Gerundet: -0.41
0.4692670451281495, Gerundet: 0.47
0.3930761232602988, Gerundet: 0.39


### LU-Zerlegung

In [18]:
P, L, U = lu(A)
print(f'Permutationsmatrix:\n{P}')
print('\nL, U:')
print(f'L:\n{L}')
print(f'U:\n{U}')
print('\nL, U Gerundet:')
print(f'L:\n{np.around(L, 2)}')
print(f'U:\n{np.around(U, 2)}')

Permutationsmatrix:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

L, U:
L:
[[ 1.          0.          0.        ]
 [ 0.4         1.          0.        ]
 [ 1.         -0.55555556  1.        ]]
U:
[[5.         3.         5.        ]
 [0.         1.8        2.        ]
 [0.         0.         5.11111111]]

L, U Gerundet:
L:
[[ 1.    0.    0.  ]
 [ 0.4   1.    0.  ]
 [ 1.   -0.56  1.  ]]
U:
[[5.   3.   5.  ]
 [0.   1.8  2.  ]
 [0.   0.   5.11]]
