In [12]:
import numpy as np
import numpy.linalg as la
from scipy.linalg import lu

In [13]:
# Matrizen definieren, Inverse, Eigenwerte usw. wird nur von Matrix A berechnet
A = np.array([
    [-2, 3, -4],
    [-1, -6, -3],
    [2, 6, 1]
])
B = np.array([
    [1, 3, 5],
    [5, 2, 9],
    [2, 3, 4]
])
a = np.array(
    [1, 2, 3]
)

print(f'A = \n {A}')
print(f'B = \n {B}')

A = 
 [[-2  3 -4]
 [-1 -6 -3]
 [ 2  6  1]]
B = 
 [[1 3 5]
 [5 2 9]
 [2 3 4]]


### Determinante

In [14]:
det = la.det(A)
print(f'{det}, Gerundet: {round(det, 2)}')

-63.00000000000005, Gerundet: -63.0


### Inverse

In [15]:
inv = la.inv(A)
print(f'Inverse:\n{inv}')
print(f'Gerundet:\n{np.around(inv, 2)}')

Inverse:
[[-0.19047619  0.42857143  0.52380952]
 [ 0.07936508 -0.0952381   0.03174603]
 [-0.0952381  -0.28571429 -0.23809524]]
Gerundet:
[[-0.19  0.43  0.52]
 [ 0.08 -0.1   0.03]
 [-0.1  -0.29 -0.24]]


### Transformation

In [16]:
A.T

array([[-2, -1,  2],
       [ 3, -6,  6],
       [-4, -3,  1]])

### Rang

In [23]:
la.matrix_rank(A)

3

### Matrixmultiplikation

In [17]:
np.matmul(A, B)

array([[  5, -12,   1],
       [-37, -24, -71],
       [ 34,  21,  68]])

### Matrix mit Vektor multiplizieren

In [18]:
np.matmul(A, a)

array([ -8, -22,  17])

### Eigenwerte

In [19]:
eigenwerte = la.eigvals(A)
for i, eig in enumerate(eigenwerte):
    print(f'Lambda {i+1}: {eig}, Gerundet: {round(eig, 2)}')

Lambda 1: (-1.9999999999999982+4.123105625617662j), Gerundet: (-2+4.12j)
Lambda 2: (-1.9999999999999982-4.123105625617662j), Gerundet: (-2-4.12j)
Lambda 3: (-2.9999999999999982+0j), Gerundet: (-3+0j)


c:\Users\chatr\Documents\Studium\6_Semester\LIAL\linalg_notebooks\.venv\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: The Python built-in `round` is deprecated for complex scalars, and will raise a `TypeError` in a future release. Use `np.round` or `scalar.round` instead.
  This is separate from the ipykernel package so we can avoid doing imports until


### Eigenvektoren

In [20]:
eigenvektoren = la.eig(A)[1]
for i, eig in enumerate(eigenvektoren):
    print(f'Vektor {i+1}:')
    for v in eig:
        print(f'{v}, Gerundet: {round(v, 2)}')

Vektor 1:
(0.7646867088630902+0j), Gerundet: (0.76+0j)
(0.7646867088630902-0j), Gerundet: (0.76-0j)
(-0.9486832980505138+0j), Gerundet: (-0.95+0j)
Vektor 2:
(0.08865932856383676+0.3198578043194091j), Gerundet: (0.09+0.32j)
(0.08865932856383676-0.3198578043194091j), Gerundet: (0.09-0.32j)
(0.3162277660168382+0j), Gerundet: (0.32+0j)
Vektor 3:
(0.0664944964228772-0.5483276645475585j), Gerundet: (0.07-0.55j)
(0.0664944964228772+0.5483276645475585j), Gerundet: (0.07+0.55j)
(5.177826122042654e-16+0j), Gerundet: 0j


c:\Users\chatr\Documents\Studium\6_Semester\LIAL\linalg_notebooks\.venv\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: The Python built-in `round` is deprecated for complex scalars, and will raise a `TypeError` in a future release. Use `np.round` or `scalar.round` instead.
  """


### LU-Zerlegung

In [21]:
P, L, U = lu(A)
print(f'Permutationsmatrix:\n{P}')
print('\nL, U:')
print(f'L:\n{L}')
print(f'U:\n{U}')
print('\nL, U Gerundet:')
print(f'L:\n{np.around(L, 2)}')
print(f'U:\n{np.around(U, 2)}')

Permutationsmatrix:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

L, U:
L:
[[ 1.          0.          0.        ]
 [-1.          1.          0.        ]
 [ 0.5        -0.83333333  1.        ]]
U:
[[-2.   3.  -4. ]
 [ 0.   9.  -3. ]
 [ 0.   0.  -3.5]]

L, U Gerundet:
L:
[[ 1.    0.    0.  ]
 [-1.    1.    0.  ]
 [ 0.5  -0.83  1.  ]]
U:
[[-2.   3.  -4. ]
 [ 0.   9.  -3. ]
 [ 0.   0.  -3.5]]
