In [25]:
import numpy as np
import numpy.linalg as la
import fractions

# Uncomment for fractions
# np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())}) 

# Uncomment for decimals
np.set_printoptions(formatter={})

In [26]:
# Matrix definieren
A = np.array([
    [3, 5],
    [1, 7]
])

print(f'A = \n {A}')

A = 
 [[3 5]
 [1 7]]


### Eigenschaften

In [27]:
# Determinante
det = la.det(A)
print(f'Determinante: {det}, gerundet: {round(det, 4)}')

# Inverse
inv = la.inv(A)
print(f'\nInverse:\n{np.around(inv, 4)}')

# Transformation
print(f'\nTransformation:\n{A.T}') 

# Rang
print(f'\nRang:\n{la.matrix_rank(A)}')

Determinante: 16.000000000000007, gerundet: 16.0

Inverse:
[[ 0.4375 -0.3125]
 [-0.0625  0.1875]]

Transformation:
[[3 1]
 [5 7]]

Rang:
2
