In [115]:
import numpy as np
import numpy.linalg as la
from scipy.linalg import lu
import fractions

# Uncomment for fractions
# np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())}) 

# Uncomment for decimals
np.set_printoptions(formatter={})

In [116]:
# Matrizen definieren
A = np.array([
    [3, 5],
    [1, 7]
])
B = np.array([
    [3, 5],
    [1, 7]
])
a = np.array(
    [1, 2]
)

print(f'A = \n {A}')
print(f'B = \n {B}')

A = 
 [[3 5]
 [1 7]]
B = 
 [[3 5]
 [1 7]]


### Matrixmultiplikation

In [117]:
np.matmul(A, B)

array([[14, 50],
       [10, 54]])

### Matrix mit Vektor multiplizieren

In [118]:
np.matmul(A, a)

array([13, 15])