In [119]:
import numpy as np
import numpy.linalg as la
from scipy.linalg import lu
import fractions

# Uncomment for fractions
# np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())}) 

# Uncomment for decimals
np.set_printoptions(formatter={})

In [120]:
# Matrizen definieren
A = np.array([
    [[-2.5, -2.5],
    [-0.5, -1.5],
    [ 0.5,  0.5],
    [ 2.5,  3.5]]
])
B = np.array([
    [4.3333, 4.3333],
    [5.3333, 7]
])
a = np.array(
    [1, 2]
)

print(f'A = \n {A}')
print(f'B = \n {B}')

A = 
 [[[-2.5 -2.5]
  [-0.5 -1.5]
  [ 0.5  0.5]
  [ 2.5  3.5]]]
B = 
 [[4.3333 4.3333]
 [5.3333 7.    ]]


### Matrixmultiplikation

In [121]:
np.matmul(A, B)

array([[[-24.1665 , -28.33325],
        [-10.1666 , -12.66665],
        [  4.8333 ,   5.66665],
        [ 29.4998 ,  35.33325]]])

### Matrix mit Vektor multiplizieren

In [122]:
np.matmul(A, a)

array([[-7.5, -3.5,  1.5,  9.5]])