In [262]:
import numpy as np
import numpy.linalg as la

In [263]:
# Matrix definieren
A = np.array([
    [1, 1],
    [3, 2],
    [4, 4],
    [6, 7]
])  

print(f'A = \n {A}')

A = 
 [[1 1]
 [3 2]
 [4 4]
 [6 7]]


### Singularwertzerlegung

In [264]:
svd = la.svd(A)

print(f'U:\n{np.around(svd[0], 4)}\n')
print('SIGMA (muss als Diagonalmatrix mit gleichen Dimensionen wie A geschrieben werden):')
s = A.shape
S = svd[1]
Z = np.zeros(s)
np.fill_diagonal(Z, S)

print(f'S:\n{Z}\n')
print(f'V:\n{np.around(svd[2], 4)}')

U:
[[-0.1234 -0.0464 -0.4842 -0.865 ]
 [-0.3067 -0.8707 -0.2898  0.2527]
 [-0.4938 -0.1856  0.7731 -0.3523]
 [-0.8043  0.4531 -0.2898  0.2527]]

SIGMA (muss als Diagonalmatrix mit gleichen Dimensionen wie A geschrieben werden):
S:
[[11.45089344  0.        ]
 [ 0.          0.93650381]
 [ 0.          0.        ]
 [ 0.          0.        ]]

V:
[[-0.685  -0.7285]
 [-0.7285  0.685 ]]
