In [108]:
import numpy as np
import numpy.linalg as la

In [109]:
# Matrix definieren
A = np.array([
    [3, 2, 2],
    [2, 3, -2]
])

print(f'A = \n {A}')

A = 
 [[ 3  2  2]
 [ 2  3 -2]]


### Singularwertzerlegung

In [114]:
svd = la.svd(A)

print(f'U:\n{np.around(svd[0], 4)}\n')
print('SIGMA (muss als Diagonalmatrix mit gleichen Dimensionen wie A geschrieben werden):')
s = A.shape
I = np.eye(s[0], s[1])
S = I@np.diag(svd[1]@I)
print(f'S:\n{S}\n')
print(f'V:\n{np.around(svd[2], 4)}')

U:
[[-0.7071 -0.7071]
 [-0.7071  0.7071]]

SIGMA (muss als Diagonalmatrix mit gleichen Dimensionen wie A geschrieben werden):
S:
[[5. 0. 0.]
 [0. 3. 0.]]

V:
[[-0.7071 -0.7071 -0.    ]
 [-0.2357  0.2357 -0.9428]
 [-0.6667  0.6667  0.3333]]

 A am Afang:
[[ 3  2  2]
 [ 2  3 -2]]
A:
[[ 3.  2.  2.]
 [ 2.  3. -2.]]
