In [259]:
import numpy as np
import numpy.linalg as la

In [260]:
# Matrix definieren
A = np.array([
    [-2.5, -2.5],
    [-0.5, -1.5],
    [ 0.5,  0.5],
    [ 2.5,  3.5]
])

print(f'A = \n {A}')

A = 
 [[-2.5 -2.5]
 [-0.5 -1.5]
 [ 0.5  0.5]
 [ 2.5  3.5]]


### Singularwertzerlegung

In [261]:
svd = la.svd(A)

print(f'U:\n{np.around(svd[0], 4)}\n')
print('SIGMA (muss als Diagonalmatrix mit gleichen Dimensionen wie A geschrieben werden):')
s = A.shape
S = svd[1]
Z = np.zeros(s)
np.fill_diagonal(Z, S)

print(f'S:\n{Z}\n')
print(f'V:\n{np.around(svd[2], 4)}')

U:
[[-0.6063  0.6063  0.1598  0.4891]
 [-0.2575 -0.7425 -0.0465  0.6166]
 [ 0.1213 -0.1213  0.985  -0.0211]
 [ 0.7425  0.2575 -0.0465  0.6166]]

SIGMA (muss als Diagonalmatrix mit gleichen Dimensionen wie A geschrieben werden):
S:
[[5.78726382 0.        ]
 [0.         0.71244473]
 [0.         0.        ]
 [0.         0.        ]]

V:
[[ 0.6154  0.7882]
 [-0.7882  0.6154]]
