In [1]:
import numpy as np

In [2]:
# Vektoren definieren
a = np.array ([2, 2, 5])
b = np.array ([2, 1, 9])

print (f'a = \n{a}')
print (f'b = \n{b}')

a = 
[2 2 5]
b = 
[2 1 9]


### Addition

In [3]:
a + b

array([ 4,  3, 14])

### Skalarprodukt
a • b <br>
Wenn das Skalarprodukt zweier Vektoren 0 sind stehen sie senkrecht (orthogonal) aufeinander.

In [4]:
np.dot(a, b)

51

### Vektorprodukt/Kreuzprodukt
a x b


In [5]:
np.cross(a, b)

array([13, -8, -2])

### Vektorskalierung
Zahl * Vektor = Streckung oder Stauchung des Vektors

In [6]:
s = 4 # s = Streckungsfaktor
a * s

array([ 8,  8, 20])

### Vektornormierung / Einheitsvektor

In [7]:
norm = np.linalg.norm(a)
print(f'Länge des Vektors: {norm}, Gerundet: {round(norm, 4)}')
print(f'Normierter Vektor: {a/norm}, Gerundet: {np.around(a/norm, 4)}')

Länge des Vektors: 5.744562646538029, Gerundet: 5.7446
Normierter Vektor: [0.34815531 0.34815531 0.87038828], Gerundet: [0.3482 0.3482 0.8704]
